FROM python:3.10

CMD ["pip", "install", "--upgrade", "pip"]

WORKDIR /app

RUN apt-get install gcc libmariadb3 libmariadb-dev libmariadb-dev-compat -y

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app

EXPOSE 8080

CMD ["python3", "main.py"]
