FROM python:3.10-slim-buster

CMD ["pip", "install", "--upgrade", "pip"]

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app

EXPOSE 8080

CMD ["python3", "main.py"]
